### ISSUE TITLE
The live url is not working

### ISSUE THREAD

**Issue by saurabhpandey9** [buddyeorl/deep-talk#1]
Hi,
can you please tell me if this project works for an offline mode without internet? I just want to know whether this project can convert speech to text if the node server is not running on the same machine, and the website still converts speech to text without the internet. 

It would be very helpful if you can answer.

your live demo URL is also not working.

Thanks

**Comment by buddyeorl** [comment]
Hi there, I took the demo down, but will have it up later today if you want to do some live testing. 

Answering your question, If you set a local node server the app will convert the speech to text without internet.

**Comment by saurabhpandey9** [comment]
would be very helpful if you can up it for a day.

**Comment by buddyeorl** [comment]
will do, will let you know when is ready, shouldn't take long.
